/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GUI_LabelTool */

#ifndef _Included_GUI_LabelTool
#define _Included_GUI_LabelTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GUI_LabelTool
 * Method:    getRpdDesign
 * Signature: (Lorg/apache/jena/ontology/OntModel;Lorg/opencv/core/Mat;)Lorg/opencv/core/Mat;
 */
JNIEXPORT jobject JNICALL Java_GUI_LabelTool_getRpdDesign__Lorg_apache_jena_ontology_OntModel_2Lorg_opencv_core_Mat_2
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     GUI_LabelTool
 * Method:    getRpdDesign
 * Signature: (Lorg/apache/jena/ontology/OntModel;)Lorg/opencv/core/Mat;
 */
JNIEXPORT jobject JNICALL Java_GUI_LabelTool_getRpdDesign__Lorg_apache_jena_ontology_OntModel_2
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
